<?php
/**
 * @file event_sign module file
 * author: yani@bellcom.dk
 */


function forum_notification_form_alter(&$form, &$form_state, $form_id) {
  global $user;
  if ($form_id == 'user_register_form' || ($form_id == 'user_profile_form' && $form['#user_category'] == 'account')) {
    // Form element. It's a fieldset , "Toggle display"
    $form['forum_update_user_settings'] = array(
      '#type' => 'fieldset',
      '#title' => t('Forum Notification'),
      '#collapsible' => TRUE,
    );
    //dpm($form);
    //$form['locations'][0]['#title'] = "Fakuraadresse";
    $data = forum_forum_load();
    //print_r($data);

    $newdata = $init = array();
    foreach ($data->forums as $tid => $item) {
      $forum_name = $item->name;
      $newdata[$tid] = t($forum_name);
      $init[$tid] = $tid;
    }

    // Check if there is a record in database.
    $uri = current_path();
    $uri_0 = preg_split("/\//",$uri);
    if (isset($uri_0[1]) && is_numeric($uri_0[1])) {
      $notify = forum_notification_load_by_uid($uri_0[1]);
    }
    if (isset($notify->changes_forums)) {
      $val_1 = unserialize($notify->changes_forums);
    }
    else {
      $val_1 = $init;
    }
    $val_2 = isset($notify->frequency) ? $notify->frequency : 2;

    $newdata_2 = array(
                  '0' => t('Never'),
                  '1' => t('Daily'),
                  '2' => t('Weekly'),
                  '3' => t('Monthly'),
                  '4' => t('Live'),

                       );
    $form['forum_update_user_settings']['forum_update_user_frequency'] = array(
      '#type' => 'select',
      '#title' => t('Forum notification frequency'),
      '#options' => $newdata_2,
      '#description' => t('Choose notification frequency, default is weekly'),
      '#default_value' => $val_2,

    );
    $form['forum_update_user_settings']['forum_update_user_options'] = array(
      '#type' => 'checkboxes',
      '#title' => t('Forum notification options'),
      '#options' => $newdata,
      '#description' => t('Check or uncheck the respective fields'),
      '#default_value' => $val_1,
    );
  }
}

/**
 * Implements hook_user_presave().
 *
 * User data (forum nitification).
 * This function handles existing user account, forum_notification_user_insert takes
 * care of new accounts.
 * @see forum_notification_user_insert()
 */
function forum_notification_user_presave(&$edit, $account, $category) {
  switch ($category) {
    case 'account':
      // We only process existing accounts.
      if (!empty($account->uid)) {
        $notify = forum_notification_load_by_uid($account->uid);
        if ($notify) {
          $notify->uid = $account->uid;
          // Update mail, status and language if they are changed.
          if (isset($edit['mail'])) {
            $notify->mail = $edit['mail'];
          }
          if (isset($edit['forum_update_user_options'])) {
            $notify->changes_forums = serialize($edit['forum_update_user_options']);
          }
          if (isset($edit['forum_update_user_frequency'])) {
            $notify->frequency = $edit['forum_update_user_frequency'];
          }
          forum_notification_save($notify);

        }
        elseif (isset($edit['mail']) && !empty($edit['mail'])) {
          $query = db_insert('forum_notification')
            ->fields(array(
            'mail' => $edit['mail'],
            'uid' => $account->uid,
            'frequency' => $edit['forum_update_user_frequency'],
            'changes_forums' => serialize(isset($edit['forum_update_user_options']) ? $edit['forum_update_user_options'] : array()),
            'created' => REQUEST_TIME,
          ));
          $last_insert_id = $query->execute();
        }
      }
      break;
  }
}


/**
 * Load a forum notification object.
 *
 * @param $uid
 *    user id.
 * @return
 *   forum notification object, FALSE if user does not want be notified.
 *
 */
function forum_notification_load_by_uid($uid) {
  $result = db_query("SELECT * FROM {forum_notification} WHERE uid = $uid")->fetchObject();;

  return isset($result) ? $result: FALSE;
}


/**
 * Store forum notification object in the database.
 */
function forum_notification_save(&$notify) {
  if (!empty($notify->nnid)) {
    db_update('forum_notification')
      //->key(array('tid' => $category->tid))
      ->condition('nnid', $notify->nnid)
      ->fields(array(
        'nnid' => $notify->nnid,
        'mail' => $notify->mail,
        'uid' => $notify->uid,
        'frequency' => $notify->frequency,
        'changes_forums' => $notify->changes_forums,
      ))
      ->execute();

  }
  elseif (empty($notify->nnid)) {
    $query = db_insert('forum_notification')
      ->fields(array(
      'mail' => $notify->mail,
      'uid' => $notify->uid,
      'frequency' => $notify->frequency,
      'changes_forums' => $notify->changes_forums,
      'created' => REQUEST_TIME,
      ));
    $last_insert_id = $query->execute();
    if ($last_insert_id !== FALSE) {
      $notify->nnid = $last_insert_id;

    }
  }
}

/**
 * Implements hook_user_insert().
 *
 * Update uid and preferred language when the new account was already subscribed.
 */
function forum_notification_user_insert(&$edit, $account, $category) {
  // Use the email address to check if new account is already notified.
  $notify = forum_notification_load_by_uid($edit['uid']);
  // If the user is notified, return. 
  if ($notify) {
    return;
  }

  // Process forum notification check boxes.
  if (isset($edit['forum_update_user_frequency'])) {
    $query = db_insert('forum_notification')
            ->fields(array(
            'mail' => $edit['mail'],
            'uid' => $account->uid,
            'frequency' => $edit['forum_update_user_frequency'],
            'changes_forums' => serialize(isset($edit['forum_update_user_options']) ? $edit['forum_update_user_options'] : array()),
            'created' => REQUEST_TIME,
    ));
    $last_insert_id = $query->execute();
  }
}

/**
 * Implements hook_user_delete().
 */
function forum_notification_user_delete($account) {
  // Delete notification when account is removed.
  $notify = forum_notification_load_by_uid($account->uid);
  if ($notify) {
    forum_notification_delete($notify);
  }
}
/**
 * Delete notification from the database.
 *
 * @param $nnid
 *   notification object.
 *
 */
function forum_notification_delete(stdClass $notify) {

  db_delete('forum_notification')
    ->condition('uid', $notify->uid)
    ->execute();

}
/*
 *Implement hook_menu()
 *
 */
function forum_notification_menu() {
  $items = array();
  $items['forum_notification/test'] = array(
    'title' => 'Forum notification test',
  //  'type' => MENU_CALLBACK,
   // 'page callback' => 'drupal_get_form',
    'page callback' => 'forum_notification_prepare_mail',
    'access arguments' => array('administer site configuration'),
  );
  return $items;
}

function forum_notification_prepare_mail() {
  print  $last_send_time = variable_get('last_sent_time','2011-12-31');

  print $date = date('Y-m-d');
  if ($last_send_time == $date) {
    drupal_set_message("Mails er allerede blevet sendt i dag");
    drupal_goto("/");
    break;
  }
  if ($date > $last_send_time) {
    print  $time = strtotime($last_send_time);
    $results = db_query("SELECT nid FROM {node} WHERE type= 'forum' and created >= $time")->fetchAll();
    print_r($results);
    $new_node = array();
    if ($results) {
      foreach ($results as $node) {
        $node = node_load($node->nid);
        $tid = $node->taxonomy_forums['und'][0]['tid'];
  
         print $new_node[$tid][] = $node;

      }
      $result = forum_notification_sendmail($new_node);
    }
    else {
      drupal_set_message("Der er ingen ny forumemner.", 'status');
      drupal_goto("<front>");
    }
  }
  //print_r($new_node);
 // $result = forum_notification_send_mail($new_node);
  //$last_send_time = variable_set('last_send_time',$date);
}
function forum_notification_sendmail($new_node) {

  if (empty($new_node)) {
    return;
  }
  global $language;
  // Send a email for each forum.
  foreach ($new_node as $tid => $nodes) {
    $forum = taxonomy_term_load($tid);
    print $forum->name;
    $body = "<div style='font-size: 32px; font-weight: bold; margin: 30px 30px;'> Nye forumemner i ". $forum->name ."på itchefer.dk</div>" . "<hr />";
    foreach ($nodes as $key => $node) {
      $body = $body . "<h3>".$node->title."</h3>";
      $body = $body . "<div>". $node->body['und'][0]['value'] ."</div><hr>";
    }
    $body;
    $params = array(
      'subject' => "Forum - " . $forum->name ." nye emner notifikation",
      'message' => $body,
    );
    // Get mail from user who subscrips the forum notification.
    $users = db_query("SELECT * FROM {forum_notification}")->fetchAll();

    $mail_list = "";
    foreach ($users as $key => $user) {

      $forum_array = unserialize($user->changes_forums);
      if ($forum_array[$tid] != 0) {
        if ($mail_list == "")
          $mail_list = $mail_list.$user->mail;
        else
          $mail_list = $mail_list. ",".$user->mail;
      }
    }
   //variable_set('mail_system', array('default-system' => 'DefaultMailSystem', 'forum_notification' => 'ExampleMailSystem'));
   $from = variable_get('site_mail', 'mail@itchefer.dk');
   $re= drupal_mail('forum_notification', 'notice', $mail_list, $language, $params, $from, TRUE);
  //print $re;
  }
  drupal_set_message('Mails udsendt.', 'status');
  drupal_goto("<front>");
}
/*
 * Implement hook_mail()
 */
function forum_notification_mail($key,&$message, $params) {
  global $language;
  $from = variable_get('site_mail', 'mail@itchefer.dk');
  $variables = array(
    '!site-name' => variable_get('site_name','Itchefer.dk'),
    '!subject' => $params['subject'],
    '!category' => isset($params['category']['category']) ? $params['category']['category'] : '',
    '!form-url' => url($_GET['q'], array('absolute' => TRUE, 'language' => $language)),
    '!sender-name' => "itchefer.dk",
    '!sender-url' => $from,


  );
  switch ($key) {
     case 'notice':
      $message['subject'] .= t($params['subject'], array('langcode' => $language));
      $message['body'][] = $params['message'] ;
      break;

  }

}
